### ISSUE TITLE
Where are the contracts?

### ISSUE THREAD

**Issue by naddika** [Sparrowswap/sparrowswap-contracts#2]
The link to the contracts in README is dead. Where are the contracts? How can I interract with, let's say, staking one?

**Comment by peyton** [comment]
hey, the staking contracts will be changed for mainnet. i’m curious how we can support you. let’s continue the conversation on telegram. please DM @BarnacleBull

**Comment by BarnacleBull** [comment]
hey @naddika redoing the staking contracts for mainnet. shoot me a telegram message at @barnaclebull and i can help you out

**Comment by BarnacleBull** [comment]
Hi, closing. Please feel free to reach out to @BarnacleBull on Telegram for assistance.
